AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.2.2
  Exclude:
      - 'spec/**/*'
      - 'lib/capybara/spec/**/*'
      - 'capybara.gemspec'

#################### Lint ################################

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

Metrics/AbcSize:
  Max: 53

Metrics/ClassLength:
  Max: 460

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/MethodLength:
  Max: 29

Metrics/ModuleLength:
  Max: 194

Metrics/PerceivedComplexity:
  Max: 19

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/capybara/driver/base.rb'
    - 'lib/capybara/driver/node.rb'

Lint/HandleExceptions:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/PredicateName:
  Exclude:
    - '**/*/*matchers.rb'

Style/RescueStandardError:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/RedundantReturn:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end
